version: '2.2'

services:

  front:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}nginx:${MAILU_VERSION:-2024.06}
    restart: always
    env_file: mailu.env
    networks:
      - default
      - traefik-proxy # Connect to your Traefik network
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-proxy"

      # --- Web UI & Webmail HTTP to HTTPS Redirect ---
      - "traefik.http.routers.mailu-http.rule=Host(`${HOSTNAMES}`)"
      - "traefik.http.routers.mailu-http.entrypoints=web"
      - "traefik.http.routers.mailu-http.middlewares=https-redirect@file"

      # --- Web UI & Webmail HTTPS Configuration ---
      - "traefik.http.routers.mailu-https.rule=Host(`${HOSTNAMES}`)"
      - "traefik.http.routers.mailu-https.entrypoints=websecure"
      - "traefik.http.routers.mailu-https.tls=true"
      - "traefik.http.routers.mailu-https.tls.certresolver=letsencrypt"
      - "traefik.http.routers.mailu-https.service=mailu-service"
      - "traefik.http.services.mailu-service.loadbalancer.server.port=80"
      
      # --- Mail Ports (TCP Passthrough) ---
      - "traefik.tcp.routers.smtp.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.smtp.entrypoints=smtp"
      - "traefik.tcp.routers.smtp.service=smtp-service"
      - "traefik.tcp.services.smtp-service.loadbalancer.server.port=25"

      - "traefik.tcp.routers.smtps.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.smtps.entrypoints=smtps"
      - "traefik.tcp.routers.smtps.service=smtps-service"
      - "traefik.tcp.services.smtps-service.loadbalancer.server.port=465"
      - "traefik.tcp.routers.smtps.tls.passthrough=true"

      - "traefik.tcp.routers.submission.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.submission.entrypoints=submission"
      - "traefik.tcp.routers.submission.service=submission-service"
      - "traefik.tcp.services.submission-service.loadbalancer.server.port=587"

      - "traefik.tcp.routers.imaps.rule=HostSNI(`*`)"
      - "traefik.tcp.routers.imaps.entrypoints=imaps"
      - "traefik.tcp.routers.imaps.service=imaps-service"
      - "traefik.tcp.services.imaps-service.loadbalancer.server.port=993"
      - "traefik.tcp.routers.imaps.tls.passthrough=true"

  # --- Other Mailu Services (No changes needed) ---
  admin:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}admin:${MAILU_VERSION:-2024.06}
    restart: always
    env_file: mailu.env
    volumes:
      - "/mailu/data:/data"
      - "/mailu/dkim:/dkim"
    networks:
      - default
    depends_on:
      - front

  imap:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}dovecot:${MAILU_VERSION:-2024.06}
    restart: always
    env_file: mailu.env
    volumes:
      - "/mailu/mail:/mail"
    networks:
      - default
    depends_on:
      - front

  smtp:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}postfix:${MAILU_VERSION:-2024.06}
    restart: always
    env_file: mailu.env
    volumes:
      - "/mailu/overrides/postfix:/overrides:ro"
    networks:
      - default
    depends_on:
      - front

  webmail:
    image: ${DOCKER_ORG:-mailu}/${DOCKER_PREFIX:-}roundcube:${MAILU_VERSION:-2024.06}
    restart: always
    env_file: mailu.env
    volumes:
      - "/mailu/webmail:/data"
    networks:
      - default
    depends_on:
      - imap

# --- Define Networks ---
networks:
  default:
  traefik-proxy: # Connect to Traefik's external network
    external: true
